# Generated by Django 5.2.7 on 2026-05-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0001_initial'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='t_notificacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_usuario_destino',
            field=models.ForeignKey(blank=True, db_column='id_usuario_destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_destino', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['id_usuario_destino'], name='idx_notificaciones_usuario'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida'], name='idx_notificaciones_leida'),
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
    ]
