# Generated by Django 5.2.7 on 2026-05-30 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_descripcion_alter_categoria_id_and_more'),
        ('promocion', '0001_initial'),
        ('supermercado', '0002_supermercado_created_at_supermercado_updated_at_and_more'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='foto_es_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocion',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='condicion_producto',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('reacondicionado', 'Reacondicionado')], default='nuevo', max_length=30),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id_supermercado',
            field=models.ForeignKey(db_column='id_supermercado', on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='supermercado.supermercado'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id_tipo_promocion',
            field=models.ForeignKey(db_column='id_tipo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='promocion.tipopromocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocionhorario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopromocion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipopromocion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopromocion',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['estado'], name='idx_promociones_estado'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['id_categoria'], name='idx_promociones_categoria'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['id_supermercado'], name='idx_promociones_supermercado'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['id_usuario'], name='idx_promociones_usuario'),
        ),
        migrations.AddIndex(
            model_name='promocionhorario',
            index=models.Index(fields=['codigo_promocion'], name='idx_horarios_promocion'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='chk_promocion_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__isnull', True), models.Q(('descuento__gte', 0), ('descuento__lte', 100)), _connector='OR'), name='chk_promocion_descuento_rango'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(condition=models.Q(('vistas__gte', 0)), name='chk_promocion_vistas_no_negativas'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_fechas_promocion'),
        ),
        migrations.AddConstraint(
            model_name='promocionhorario',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_rango'),
        ),
        migrations.AlterModelTable(
            name='promocion',
            table='promociones',
        ),
        migrations.AlterModelTable(
            name='promocionhorario',
            table='promociones_horarios',
        ),
        migrations.AlterModelTable(
            name='tipopromocion',
            table='tipos_promocion',
        ),
    ]
