# Generated by Django 5.2.7 on 2026-05-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_promocion_created_at_promocion_foto_es_local_and_more'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
        ('valoracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='codigo_promocion',
            field=models.ForeignKey(db_column='codigo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='promocion.promocion'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuario.usuario'),
        ),
        migrations.AddIndex(
            model_name='valoracion',
            index=models.Index(fields=['codigo_promocion'], name='idx_valoraciones_promocion'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'codigo_promocion'), name='uq_valoracion_usuario_promocion'),
        ),
        migrations.AddConstraint(
            model_name='valoracion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['positiva', 'negativa'])), name='chk_tipo_valoracion'),
        ),
        migrations.AlterModelTable(
            name='valoracion',
            table='valoraciones',
        ),
    ]
