# Generated by Django 5.2.7 on 2026-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorito', '0001_initial'),
        ('promocion', '0002_promocion_created_at_promocion_foto_es_local_and_more'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['id_usuario'], name='idx_favoritos_usuario'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['codigo_promocion'], name='idx_favoritos_promocion'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'codigo_promocion'), name='uq_favorito_usuario_promocion'),
        ),
        migrations.AlterModelTable(
            name='favorito',
            table='favoritos',
        ),
    ]
