# Generated by Django 5.2.7 on 2026-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_promocion_created_at_promocion_foto_es_local_and_more'),
        ('reporte', '0001_initial'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado'], name='idx_reportes_estado'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['codigo_promocion'], name='idx_reportes_promocion'),
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reportes',
        ),
    ]
