# Generated by Django 5.2.7 on 2026-05-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('promocion', '0002_promocion_created_at_promocion_foto_es_local_and_more'),
        ('usuario', '0002_usuario_ciudad_usuario_created_at_usuario_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='codigo_promocion',
            field=models.ForeignKey(db_column='codigo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='promocion.promocion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuario.usuario'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['codigo_promocion'], name='idx_comentarios_promocion'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['id_usuario'], name='idx_comentarios_usuario'),
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='comentarios',
        ),
    ]
